---
deployment:
  tasks:
    - export HOME=/home/abcaqnid
    - export PATH=$PATH:$HOME/.nvm/versions/node/v18.18.2/bin/
    - npm install
    - npm run build
    - /bin/cp -R dist/* /home/abcaqnid/public_html/ 