---
deployment:
  tasks:
    - export DEPLOYPATH=/home/abcaqnid/public_html/
    - cd /home/abcaqnid/repositories/eco-yard-care-web
    - /home/abcaqnid/nodevenv/repositories/eco-yard-care-web/20/bin/npm install
    - /home/abcaqnid/nodevenv/repositories/eco-yard-care-web/20/bin/npm run build
    - /bin/cp -R dist/. $DEPLOYPATH 