version: '3.8'

services:
  eco-yard-care-web:
    build: .
    ports:
      - "3000:80"
    volumes:
      # Mount source code for hot-reloading
      # - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - eco-yard-care-backend

  eco-yard-care-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001 