version: '3.8'

services:
  eco-yard-care-web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot-reloading
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true 